site_name: Open Source guideline for Development Cooperation projects
theme:
  name: material
  features:
    - navigation.top
    - navigation.sections
    - navigation.footer
    - navigation.indexes
    - search.suggest
    - search.highlight
    - content.tabs.link
  language: en
  palette:
    - scheme: default
  
copyright: Copyright &copy; 2024 &bullet; <a href="legal_notice">Legal Notice</a> &bullet; <a href="privacy_policy">Privacy Policy</a>

nav:
  - Home: index.md
  - Introduction:
     - Disclaimer: disclaimer.md
     - Open Source in int. Development: intro.md
  - Checklists:
    - pre-project/index.md
    - IT Selection: pre-project/IT_sel_checklist.md
    - Writing ToRs: pre-project/ToR_checklist.md

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - def_list
